### ISSUE TITLE
Getting the expiry time from the token?

### ISSUE THREAD

**Issue by jeffreylo** [keratin/authn-go#17]
https://keratin.github.io/authn-server/#/guide-confirm-password indicates that authn client libraries are able to extract the expiry/auth_time from the access token to prompt the user for a password. It seems that this capability is missing, but I've likely overlooked something.

**Comment by cainlevy** [comment]
You're right! It looks like the authn-go client doesn't currently have a function to access all verified claims. It should be a simple matter of delegating to `verifier.GetVerifiedClaims`, as this function does:

https://github.com/keratin/authn-go/blob/45602e8424095484881debf5e40e2ded222e0206/authn/authn.go#L68-L74

I may not get to this right away. Are you interested in submitting a PR?

**Comment by jeffreylo** [comment]
> Are you interested in submitting a PR?

I am! I already sketched out an approach, but wanted to make sure I wasn’t missing anything before starting. Thanks, @cainlevy.
