### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by CetinSert** [keratin/authn-go#32]
If a microservice imports `github.com/keratin/authn-go/authn` and uses it without modifications, what is your intent with `LGPL` with regards to the importing microservice?

**Comment by cainlevy** [comment]
@CetinSert My understanding is that `LGPL` allows this library to be used without requiring the program importing it to publish its own source code. Does that answer your question?

**Comment by CetinSert** [comment]
Thank you for your reply!
It does answer my question.
