### ISSUE TITLE
how do you get users details?

### ISSUE THREAD

**Issue by k1ng440** [keratin/authn-go#7]
this client seems to be nothing like ruby client. how to make calls to authn?

**Comment by shashankmehra** [comment]
The HTTP API layer has not been implemented yet. Only JWT components have been.

Once you get your user's id using `authn.SubjectFrom` you can use any HTTP client on this API to get user's authn details: https://github.com/keratin/authn-server/blob/master/docs/api.md#get-account

Or you could contribute HTTP helper functions for the same. I dont think anyone is working on them as of now.

**Comment by k1ng440** [comment]
i am working on it.
